let beatles_releases = [{
    'filename': 'Piano',
    'compression algorithm': "MP3",
    'compression bit-rate': 96,
    'original file size': 7700,
    'compressed file size': 520,
    'compression ratio': 0.07,
    'link to original version': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/piano/piano.wav">Original Audio</a>', 
    'link to compressed version': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/piano/piano_1:1.MP3">Compressed Audio</a>',
    'link to residual noise': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/piano/piano_1:1_res.aiff">Residual Audio</a>',
},{
        'filename': 'Piano',
        'compression algorithm': "MP3",
        'compression bit-rate': 128,
        'original file size': 7700,
        'compressed file size': 694,
        'compression ratio': 0.1,
        'link to original version': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/piano/piano.wav">Original Audio</a>',
        'link to compressed version': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/piano/piano_1:2.mp3">Compressed Audio</a>',
        'link to residual noise': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/piano/piano_1:2_res.aiff">Residual Audio</a>',
},{
        'filename': 'Piano',
        'compression algorithm': "MP3",
        'compression bit-rate': 192,
        'original file size': 7700,
        'compressed file size': 1000,
        'compression ratio': 0.12,
        'link to original version': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/piano/piano.wav">Original Audio</a>',
        'link to compressed version': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/piano/piano_1:3.mp3">Compressed Audio</a>',
        'link to residual noise': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/piano/piano_1:3_res.aiff">Residual Audio</a>',
},{
        'filename': 'Piano',
        'compression algorithm': "MP3",
        'compression bit-rate': 320,
        'original file size': 7700,
        'compressed file size': 1700,
        'compression ratio': 0.22,
        'link to original version': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/piano/piano.wav">Original Audio</a>',
        'link to compressed version': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/piano/piano_1:4.mp3">Compressed Audio</a>',
        'link to residual noise': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/piano/piano_1:4_res.aiff">Residual Audio</a>',
    },{
        'filename': 'Piano',
        'compression algorithm': "OGG/Vorbis",
        'compression bit-rate': "low",
        'original file size': 7700,
        'compressed file size': 278,
        'compression ratio': 0.04,
        'link to original version': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/piano/piano.wav">Original Audio</a>',
        'link to compressed version': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/piano/piano_2:1.ogg">Compressed Audio</a>',
        'link to residual noise': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/piano/piano_2:1_res.ogg">Residual Audio</a>',
    },{
        'filename': 'Piano',
        'compression algorithm': "OGG/Vorbis",
        'compression bit-rate': "low-mid",
        'original file size': 7700,
        'compressed file size': 529,
        'compression ratio': 0.07,
        'link to original version': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/piano/piano.wav">Original Audio</a>',
        'link to compressed version': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/piano/piano_2:2.ogg">Compressed Audio</a>',
        'link to residual noise': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/piano/piano_2:2_res.aiff">Residual Audio</a>',
    },{
        'filename': 'Piano',
        'compression algorithm': "OGG/Vorbis",
        'compression bit-rate': "hi-mid",
        'original file size': 7700,
        'compressed file size': 1000,
        'compression ratio': 0.13,
        'link to original version': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/piano/piano.wav">Original Audio</a>',
        'link to compressed version': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/piano/piano_2:3.ogg">Compressed Audio</a>',
        'link to residual noise': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/piano/piano_2:3_res.aiff">Residual Audio</a>',
    },{
        'filename': 'Piano',
        'compression algorithm': "OGG/Vorbis",
        'compression bit-rate': "high",
        'original file size': 7700,
        'compressed file size': 2200,
        'compression ratio': 0.29,
        'link to original version': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/piano/piano.wav">Original Audio</a>',
        'link to compressed version': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/piano/piano_2:4.ogg">Compressed Audio</a>',
        'link to residual noise': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/piano/piano_2:4_res.aiff">Residual Audio</a>',
    },{
        'filename': 'Piano',
        'compression algorithm': "AC3",
        'compression bit-rate': 96,
        'original file size': 7700,
        'compressed file size': 520,
        'compression ratio': 0.07,
        'link to original version': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/piano/piano.wav">Original Audio</a>',
        'link to compressed version': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/piano/piano_3:1.ac3">Compressed Audio</a>',
        'link to residual noise': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/piano/piano_3:1_res.aiff">Residual Audio</a>',
    },{
        'filename': 'Piano',
        'compression algorithm': "AC3",
        'compression bit-rate': 128,
        'original file size': 7700,
        'compressed file size': 693,
        'compression ratio': 0.09,
        'link to original version': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/piano/piano.wav">Original Audio</a>',
        'link to compressed version': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/piano/piano_3:2.ac3">Compressed Audio</a>',
        'link to residual noise': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/piano/piano_3:2_res.aiff">Residual Audio</a>',
    },{
        'filename': 'Piano',
        'compression algorithm': "AC3",
        'compression bit-rate': 192,
        'original file size': 7700,
        'compressed file size': 1000,
        'compression ratio': 0.13,
        'link to original version': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/piano/piano.wav">Original Audio</a>',
        'link to compressed version': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/piano/piano_3:3.ac3">Compressed Audio</a>',
        'link to residual noise': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/piano/piano_3:3_res.ac3">Residual Audio</a>',
    },{
        'filename': 'Piano',
        'compression algorithm': "AC3",
        'compression bit-rate': 320,
        'original file size': 7700,
        'compressed file size': 1700,
        'compression ratio': 0.22,
        'link to original version': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/piano/piano.wav">Original Audio</a>',
        'link to compressed version': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/piano/piano_3:4.ac3">Compressed Audio</a>',
        'link to residual noise': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/piano/piano_3:4_res.aiff">Residual Audio</a>',
    },{
        'filename': 'Piano',
        'compression algorithm': "M4A/AAC",
        'compression bit-rate': "low",
        'original file size': 7700,
        'compressed file size': 1100,
        'compression ratio': 0.14,
        'link to original version': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/piano/piano.wav">Original Audio</a>',
        'link to compressed version': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/piano/piano_4:1.m4a">Compressed Audio</a>',
        'link to residual noise': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/piano/piano_4:1_res.aiff">Residual Audio</a>',
    },{
        'filename': 'Piano',
        'compression algorithm': "M4A/AAC",
        'compression bit-rate': "low-mid",
        'original file size': 7700,
        'compressed file size': 1100,
        'compression ratio': 0.14,
        'link to original version': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/piano/piano.wav">Original Audio</a>',
        'link to compressed version': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/piano/piano_4:2.m4a">Compressed Audio</a>',
        'link to residual noise': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/piano/piano_4:2_res.m4a">Residual Audio</a>',
    },{
        'filename': 'Piano',
        'compression algorithm': "M4A/AAC",
        'compression bit-rate': "hi-mid",
        'original file size': 7700,
        'compressed file size': 1100,
        'compression ratio': 0.14,
        'link to original version': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/piano/piano.wav">Original Audio</a>',
        'link to compressed version': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/piano/piano_4:3.m4a">Compressed Audio</a>',
        'link to residual noise': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/piano/piano_4:3_res.aiff">Residual Audio</a>',
    },{
        'filename': 'Piano',
        'compression algorithm': "M4A/AAC",
        'compression bit-rate': "high",
        'original file size': 7700,
        'compressed file size': 1000,
        'compression ratio': 0.14,
        'link to original version': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/piano/piano.wav">Original Audio</a>',
        'link to compressed version': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/piano/piano_4:4.m4a">Compressed Audio</a>',
        'link to residual noise': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/piano/piano_4:4_res.aiff">Residual Audio</a>',

    },{
            'filename': 'Electronic',
            'compression algorithm': "MP3",
            'compression bit-rate': 96,
            'original file size': 10000,
            'compressed file size': 684,
            'compression ratio': 0.07,
            'link to original version': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/elec/elec.wav">Original Audio</a>' , 
            'link to compressed version': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/elec/elec_1:1.mp3">Compressed Audio</a>',
            'link to residual noise': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/elec/elec_1:1_res.aiff">Residual Audio</a>',
        },{
                'filename': 'Electronic',
                'compression algorithm': "MP3",
                'compression bit-rate': 128,
                'original file size': 10000,
                'compressed file size': 912,
                'compression ratio': 0.09,
                'link to original version': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/elec/elec.wav">Original Audio</a>' ,
                'link to compressed version': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/elec/elec_1:2.mp3">Compressed Audio</a>',
                'link to residual noise': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/elec/elec_1:2_res.mp3">Residual Audio</a>',
        },{
                'filename': 'Electronic',
                'compression algorithm': "MP3",
                'compression bit-rate': 192,
                'original file size': 10000,
                'compressed file size': 1400,
                'compression ratio': 0.14,
                'link to original version': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/elec/elec.wav">Original Audio</a>' ,
                'link to compressed version': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/elec/elec_1:3.mp3">Compressed Audio</a>',
                'link to residual noise': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/elec/elec_1:3_res.aiff">Residual Audio</a>',
        },{
                'filename': 'Electronic',
                'compression algorithm': "MP3",
                'compression bit-rate': 320,
                'original file size': 10000,
                'compressed file size': 2300,
                'compression ratio': 0.23,
                'link to original version': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/elec/elec.wav">Original Audio</a>' ,
                'link to compressed version': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/elec/elec_1:4.mp3">Compressed Audio</a>',
                'link to residual noise': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/elec/elec_1:4_res.aiff">Residual Audio</a>',
            },{
                'filename': 'Electronic',
                'compression algorithm': "OGG/Vorbis",
                'compression bit-rate': "low",
                'original file size': 10000,
                'compressed file size': 376,
                'compression ratio': 0.04,
                'link to original version': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/elec/elec.wav">Original Audio</a>' ,
                'link to compressed version': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/elec/elec_2:1.ogg">Compressed Audio</a>',
                'link to residual noise': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/elec/elec_2:1_res.aiff">Residual Audio</a>',
            },{
                'filename': 'Electronic',
                'compression algorithm': "OGG/Vorbis",
                'compression bit-rate': "low-mid",
                'original file size': 10000,
                'compressed file size': 653,
                'compression ratio': 0.07,
                'link to original version': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/elec/elec.wav">Original Audio</a>' ,
                'link to compressed version': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/elec/elec_2:2.ogg">Compressed Audio</a>',
                'link to residual noise': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/elec/elec_2:2_res.aiff">Residual Audio</a>',
            },{
                'filename': 'Electronic',
                'compression algorithm': "OGG/Vorbis",
                'compression bit-rate': "hi-mid",
                'original file size': 10000,
                'compressed file size': 1300,
                'compression ratio': 0.13,
                'link to original version': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/elec/elec.wav">Original Audio</a>' ,
                'link to compressed version': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/elec/elec_2:3.ogg">Compressed Audio</a>',
                'link to residual noise': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/elec/elec_2:3_res.aiff">Residual Audio</a>',
            },{
                'filename': 'Electronic',
                'compression algorithm': "OGG/Vorbis",
                'compression bit-rate': "high",
                'original file size': 10000,
                'compressed file size': 2700,
                'compression ratio': 0.27,
                'link to original version': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/elec/elec.wav">Original Audio</a>' ,
                'link to compressed version': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/elec/elec_2:4.ogg">Compressed Audio</a>',
                'link to residual noise': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/elec/elec_2:4_res.aiff">Residual Audio</a>',
            },{
                'filename': 'Electronic',
                'compression algorithm': "AC3",
                'compression bit-rate': 96,
                'original file size': 10000,
                'compressed file size': 683,
                'compression ratio': 0.07,
                'link to original version': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/elec/elec.wav">Original Audio</a>' ,
                'link to compressed version': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/elec/elec_3:1.ac3">Compressed Audio</a>',
                'link to residual noise': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/elec/elec_3:1_res.ac3">Residual Audio</a>',
            },{
                'filename': 'Electronic',
                'compression algorithm': "AC3",
                'compression bit-rate': 128,
                'original file size': 10000,
                'compressed file size': 911,
                'compression ratio': 0.09,
                'link to original version': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/elec/elec.wav">Original Audio</a>' ,
                'link to compressed version': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/elec/elec_3:2.ac3">Compressed Audio</a>',
                'link to residual noise': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/elec/elec_3:2_res.aiff">Residual Audio</a>',
            },{
                'filename': 'Electronic',
                'compression algorithm': "AC3",
                'compression bit-rate': 192,
                'original file size': 10000,
                'compressed file size': 1400,
                'compression ratio': 0.14,
                'link to original version': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/elec/elec.wav">Original Audio</a>' ,
                'link to compressed version': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/elec/elec_3:3.ac3">Compressed Audio</a>',
                'link to residual noise': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/elec/elec_3:3_res.aiff">Residual Audio</a>',
            },{
                'filename': 'Electronic',
                'compression algorithm': "AC3",
                'compression bit-rate': 320,
                'original file size': 10000,
                'compressed file size': 2300,
                'compression ratio': 0.23,
                'link to original version': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/elec/elec.wav">Original Audio</a>' ,
                'link to compressed version': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/elec/elec_3:4.ac3">Compressed Audio</a>',
                'link to residual noise': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/elec/elec_3:4_res.ac3">Residual Audio</a>',
            },{
                'filename': 'Electronic',
                'compression algorithm': "M4A/AAC",
                'compression bit-rate': "low",
                'original file size': 10000,
                'compressed file size': 1400,
                'compression ratio': 0.14,
                'link to original version': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/elec/elec.wav">Original Audio</a>' ,
                'link to compressed version': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/elec/elec_4:1.m4a">Compressed Audio</a>',
                'link to residual noise': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/elec/elec_4:1_res.aiff">Residual Audio</a>',
            },{
                'filename': 'Electronic',
                'compression algorithm': "M4A/AAC",
                'compression bit-rate': "low-mid",
                'original file size': 10000,
                'compressed file size': 1400,
                'compression ratio': 0.14,
                'link to original version': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/elec/elec.wav">Original Audio</a>' ,
                'link to compressed version': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/elec/elec_4:2.m4a">Compressed Audio</a>',
                'link to residual noise': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/elec/elec_4:2_res.aiff">Residual Audio</a>',
            },{
                'filename': 'Electronic',
                'compression algorithm': "M4A/AAC",
                'compression bit-rate': "hi-mid",
                'original file size': 10000,
                'compressed file size': 1400,
                'compression ratio': 0.14,
                'link to original version': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/elec/elec.wav">Original Audio</a>' ,
                'link to compressed version': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/elec/elec_4:3.m4a">Compressed Audio</a>',
                'link to residual noise': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/elec/elec_4:3_res.aiff">Residual Audio</a>',
            },{
                'filename': 'Electronic',
                'compression algorithm': "M4A/AAC",
                'compression bit-rate': "high",
                'original file size': 10000,
                'compressed file size': 1400,
                'compression ratio': 0.14,
                'link to original version': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/elec/elec.wav">Original Audio</a>' ,
                'link to compressed version': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/elec/elec_4:4.m4a">Compressed Audio</a>',
                'link to residual noise': '<a href="/users/kylemacdougall/Desktop/kmacdougall/assignment_4/sounds/elec/elec_4:4_res.aiff">Residual Audio</a>',
        
          }]
  

  function discography() {
    let table = document.createElement('table');
    table.id = "beatles_table"
    for (row = 0; row < beatles_releases.length; row++) {
      tr = document.createElement('tr');
      let columns = Object.keys(beatles_releases[row]);
      for (col = 0; col < columns.length; col++) {
        td = document.createElement('td');
        tr.appendChild(td);
        td.innerHTML = beatles_releases[row][columns[col]];
      }
      table.appendChild(tr);
    }
    document.getElementById("discography_table").appendChild(table);
}